### ISSUE TITLE
Populate API Default Route

### ISSUE THREAD

**Issue by feifan-fiona** [DevOps2021-Products/products#34]
**As a** Customer,
**I need** information populated on the default route,
**So that** I can learn something useful about the API.

**Assumptions:**
The default route will be returned as a JSON string
The REST API must be running

**Acceptance Criteria:**
```
Given the REST API service is running
When I run the default route
Then useful information about the API is returned for me as a JSON string
```

**Comment by Csardon01** [comment]
@jkiley129 can you take a stab at grooming this story given the feedback we received from JR on the Homework #1 assignment? Not exactly sure how to articulate the expected behavior is for this one based on the comments.
