### ISSUE TITLE
Create a route for REST API to perform an Action

### ISSUE THREAD

**Issue by Csardon01** [DevOps2021-Products/products#42]
**As a** Product Administrator,
**I need** a disable action,
**So that** I can disable products remotely and kick-off all associated processes.

**Assumptions:**
- Steps to disable a product are known
- The disable action will be formatted in this manner:
```PUT /products/{id}/disable```

**Acceptance Criteria:**
```
Given the disable action is available
When the disable action is called on a given product
Then the associated product will be disabled
```

**Comment by Csardon01** [comment]
@jkiley129 may need some support on this story to define the acceptance criteria. I reviewed the REST API lecture slides andstill not 100% quite sure what an Action is used for.

**Comment by jkiley129** [comment]
I'm a little confused on this one as well. I think we should make a reboot one. I really don't see the use of an action for our service other than that

**Comment by jkiley129** [comment]
I added some criteria for a reboot action. I'll message JR in the morning if this is what we should be thinking about for this one

**Comment by feifan-fiona** [comment]
I met an issue while running nosetests. Could you help to take a look at my branch? @jkiley129 Thanks.
